-- AlterTable
ALTER TABLE "Character" ADD COLUMN     "avatar" TEXT,
ADD COLUMN     "def" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "str" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "attributes" DROP NOT NULL,
ALTER COLUMN "mp" SET DEFAULT 50,
ALTER COLUMN "maxMp" SET DEFAULT 50;
