-- CreateEnum
CREATE TYPE "ConsumableSubtype" AS ENUM ('HEALTH_POTION', 'MANA_POTION', 'STAMINA_POTION', 'ELIXIR', 'STRENGTH_BUFF', 'DEFENSE_BUFF', 'AGILITY_BUFF', 'INTELLIGENCE_BUFF', 'REVIVE_POTION', 'ANTIDOTE', 'CURE_POISON', 'TEMPORARY_BUFF');

-- AlterTable
ALTER TABLE "Item" ADD COLUMN     "subtype" "ConsumableSubtype";
