-- AlterTable
ALTER TABLE "Character" ADD COLUMN     "deathTimestamp" TIMESTAMP(3),
ADD COLUMN     "hp" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "isAlive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "maxHp" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "maxStamina" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "stamina" INTEGER NOT NULL DEFAULT 100;
